#include <GL/gl.h>
#include <GL/glext.h>

#ifndef DEF
#define DEF(TYPE, NAME) extern TYPE NAME;
#endif

DEF(PFNGLGENBUFFERSPROC,    glGenBuffers);
DEF(PFNGLBINDBUFFERPROC,    glBindBuffer);
DEF(PFNGLBUFFERDATAPROC,    glBufferData);
DEF(PFNGLMAPBUFFERPROC,     glMapBuffer);
DEF(PFNGLUNMAPBUFFERPROC,   glUnmapBuffer);
DEF(PFNGLDELETEBUFFERSPROC, glDeleteBuffers);

DEF(PFNGLGENVERTEXARRAYSPROC,         glGenVertexArrays);
DEF(PFNGLBINDVERTEXARRAYPROC,         glBindVertexArray);
DEF(PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray);
DEF(PFNGLVERTEXATTRIBPOINTERPROC,     glVertexAttribPointer);
DEF(PFNGLDELETEVERTEXARRAYSPROC,      glDeleteVertexArrays);
DEF(PFNGLDRAWELEMENTSINDIRECTPROC,    glDrawElementsIndirect);
DEF(PFNGLDRAWELEMENTSINSTANCEDPROC,   glDrawElementsInstanced);

DEF(PFNGLCREATESHADERPROC,     glCreateShader);
DEF(PFNGLSHADERSOURCEPROC,     glShaderSource);
DEF(PFNGLCOMPILESHADERPROC,    glCompileShader);
DEF(PFNGLGETSHADERIVPROC,      glGetShaderiv);
DEF(PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog);
DEF(PFNGLDELETESHADERPROC,     glDeleteShader);

DEF(PFNGLCREATEPROGRAMPROC,     glCreateProgram);
DEF(PFNGLUSEPROGRAMPROC,        glUseProgram);
DEF(PFNGLGETPROGRAMIVPROC,      glGetProgramiv);
DEF(PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog);
DEF(PFNGLATTACHSHADERPROC,      glAttachShader);
DEF(PFNGLLINKPROGRAMPROC,       glLinkProgram);
DEF(PFNGLDELETEPROGRAMPROC,     glDeleteProgram);

DEF(PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation);
DEF(PFNGLUNIFORMMATRIX4FVPROC,   glUniformMatrix4fv);
DEF(PFNGLUNIFORM1FPROC,          glUniform1f);
DEF(PFNGLUNIFORM1FVPROC,         glUniform1fv);
DEF(PFNGLUNIFORM3FPROC,          glUniform3f);
DEF(PFNGLUNIFORM3FVPROC,         glUniform3fv);
DEF(PFNGLUNIFORM1UIPROC,         glUniform1ui);
DEF(PFNGLUNIFORM1IPROC,          glUniform1i);
DEF(PFNGLGENERATEMIPMAPPROC,     glGenerateMipmap);

DEF(PFNGLTEXSTORAGE2DPROC,     glTexStorage2D);
DEF(PFNGLBINDIMAGETEXTUREPROC, glBindImageTexture);
DEF(PFNGLDISPATCHCOMPUTEPROC,  glDispatchCompute);
DEF(PFNGLMEMORYBARRIERPROC,    glMemoryBarrier);
DEF(PFNGLBINDBUFFERBASEPROC,   glBindBufferBase);

DEF(PFNGLDEBUGMESSAGECALLBACKPROC, glDebugMessageCallback);
DEF(PFNGLDEBUGMESSAGECONTROLPROC,  glDebugMessageControl);
#undef DEF

